name: 'license-mate'

services:

  backend:
    build:
      context: ../../
      dockerfile: docker/builds/dev-mount.Dockerfile
    image: license-mate:dev-mount
    container_name: backend
    ports:
      - '80:80'
    volumes:
      - ../../server/static:/server/static
      - ../../server/templates:/server/templates
      - ../../server/main.py:/server/main.py
      - ../../server/database.py:/server/database.py
      - ../../server/.env:/server/.env
    networks:
      - backend-network

  database:
    image: mongo:6.0
    container_name: database
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - licenseDB:/data/db
    networks:
      - backend-network

volumes:
  licenseDB:
    name: licenseDB
    driver: local

networks:
  backend-network:
    name: license-mate
    driver: bridge