name: 'flask-license-manager'

services:

  backend:
    build:
      context: ../../
      dockerfile: docker/builds/prod.Dockerfile
    image: flask-license-manager:prod
    container_name: backend
    ports:
      - '80:80'
    environment:
      MONGODB_URI: mongodb://database:27017/
    env_file:
      - ../../server/.env
    networks:
      - backend-network

  database:
    image: mongo:6.0
    container_name: database
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - licenseDB:/data/db
    networks:
      - backend-network

volumes:
  licenseDB:
    name: licenseDB
    driver: local

networks:
  backend-network:
    name: flask-license-manager
    driver: bridge