name: Docker Image Build and Deploy

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # # https://github.com/sigstore/cosign-installer
      # - name: Install cosign
      #   uses: sigstore/cosign-installer@v3.1.1
      #   with:
      #     cosign-release: 'v2.1.1'

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # https://github.com/docker/login-action#github-container-registry
      # - name: Log into registry GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ github.repository }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ vars.DOCKERFILE_PROD }}
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      # # https://github.com/sigstore/cosign
      # - name: Sign the published Docker image
      #   env:
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #   run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
